'use client';

import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import type { Prescription, Patient, Medicine } from '@/db/schema';

interface PdfExportButtonProps {
  prescription: Prescription;
  patient:      Patient;
}

export default function PdfExportButton({ prescription, patient }: PdfExportButtonProps) {
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    setLoading(true);

    // Dynamic import to keep PDF lib out of initial bundle
    const { jsPDF } = await import('jspdf');

    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const medicines = (prescription.medicinesJson as Medicine[]) ?? [];
    const tags      = (prescription.tags as string[]) ?? [];
    const findings  = (prescription.importantFindings as string[]) ?? [];

    // ── Header ──
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 22, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('ClinicOCR — Prescription Report', 15, 14);

    // ── Patient info ──
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Patient Information', 15, 32);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Name: ${patient.name}`, 15, 39);
    doc.text(`Age: ${patient.age ?? '—'}    Gender: ${patient.gender ?? '—'}    Phone: ${patient.phone ?? '—'}`, 15, 45);
    doc.text(`Date: ${new Date(prescription.createdAt).toLocaleDateString('en-IN')}`, 15, 51);

    // ── Divider ──
    doc.setDrawColor(226, 232, 240);
    doc.line(15, 56, 195, 56);

    // ── AI Summary ──
    let y = 63;
    if (prescription.aiSummary) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('AI Summary', 15, y);
      y += 7;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const summaryLines = doc.splitTextToSize(prescription.aiSummary, 180);
      doc.text(summaryLines, 15, y);
      y += summaryLines.length * 6 + 4;
    }

    // ── Medicines ──
    if (medicines.length > 0) {
      doc.line(15, y, 195, y); y += 7;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('Medicines', 15, y); y += 7;

      // Table header
      doc.setFillColor(239, 246, 255);
      doc.rect(15, y - 4, 180, 7, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(37, 99, 235);
      doc.text('Medicine', 17, y);
      doc.text('Dosage', 90, y);
      doc.text('Frequency', 140, y);
      y += 5;

      doc.setTextColor(15, 23, 42);
      medicines.forEach((med) => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        doc.text(med.name,      17,  y);
        doc.text(med.dosage,    90,  y);
        doc.text(med.frequency, 140, y);
        y += 6;
        if (y > 270) { doc.addPage(); y = 20; }
      });
      y += 3;
    }

    // ── Important Findings ──
    if (findings.length > 0) {
      doc.line(15, y, 195, y); y += 7;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('Important Findings', 15, y); y += 7;
      findings.forEach((f) => {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.text(`• ${f}`, 17, y);
        y += 6;
      });
      y += 3;
    }

    // ── Corrected Text ──
    doc.line(15, y, 195, y); y += 7;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Corrected Prescription Text', 15, y); y += 7;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const textLines = doc.splitTextToSize(prescription.correctedText ?? '', 180);
    textLines.forEach((line: string) => {
      doc.text(line, 15, y);
      y += 5;
      if (y > 270) { doc.addPage(); y = 20; }
    });

    // ── Doctor Notes ──
    let doctorNoteLineCount = 0;
    if (prescription.doctorNotes) {
      y += 3;
      doc.line(15, y, 195, y); y += 7;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('Doctor Notes', 15, y); y += 7;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      const splitNotes = doc.splitTextToSize(prescription.doctorNotes, 180);
      doctorNoteLineCount = splitNotes.length;
      doc.text(splitNotes, 15, y);
    }

    // ── Tags ──
    if (tags.length > 0) {
      y += doctorNoteLineCount * 6 + 5;
      doc.setFontSize(9);
      doc.setTextColor(71, 85, 105);
      doc.text(`Tags: ${tags.join(', ')}`, 15, y);
    }

    // ── Footer ──
    doc.setTextColor(148, 163, 184);
    doc.setFontSize(8);
    doc.text('Generated by ClinicOCR · AI-Powered Prescription Digitization Platform', 15, 290);

    doc.save(`prescription-${patient.name.replace(/\s+/g, '-')}-${new Date(prescription.createdAt).toISOString().slice(0,10)}.pdf`);
    setLoading(false);
  };

  return (
    <button onClick={handleExport} disabled={loading} className="btn-secondary">
      {loading
        ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating…</>
        : <><Download className="w-4 h-4" /> Download PDF</>
      }
    </button>
  );
}

// (helper removed — no longer needed)
